$$ y = \frac{x-E[x]}{\sqrt{Var[x]+\epsilon}}*\gamma + \beta $$

$$ x = S*q $$
$$ \gamma = S*q_{\gamma} $$
$$ \beta = S*q_{\beta}$$

$$ y = \frac{S*q-E[S*q]}{\sqrt{Var[S*q]+\epsilon}}*S*q_{\gamma} + S*q_{\beta} $$

$$ y = \frac{S(q-E[q])}{\sqrt{S^{2}(Var[q]+\frac{\epsilon}{S^2})}}*S*q_{\gamma} + S*q_{\beta} $$

$$ y = \frac{q-E[q]}{\sqrt{(Var[q]+\frac{\epsilon}{S^2})}}*S*q_{\gamma} + S*q_{\beta} $$

$$ y = S(\frac{q-E[q]}{\sqrt{(Var[q]+\frac{\epsilon}{S^2})}}*q_{\gamma} + q_{\beta}) $$

In [141]:
%load_ext autoreload
%autoreload 2
import numpy as np
import torch
from src.quant_roberta import QuantRoberta
from src.quant_ops import tensor_quant_layernorm
model = QuantRoberta()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Some weights of the model checkpoint at textattack/roberta-base-MRPC were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [142]:
inp = torch.from_numpy(np.random.uniform(size=(32,512,768))).float()

In [143]:
layernorm = model.model.roberta.encoder.layer[0].output.LayerNorm

In [144]:
gt = layernorm(inp)


In [145]:
test = tensor_quant_layernorm(layernorm, inp)

tensor([[[9357.],
         [9578.],
         [9175.],
         ...,
         [9407.],
         [9752.],
         [9539.]],

        [[9233.],
         [9199.],
         [9785.],
         ...,
         [9501.],
         [9463.],
         [9384.]],

        [[9508.],
         [9480.],
         [9362.],
         ...,
         [9416.],
         [9362.],
         [9432.]],

        ...,

        [[9349.],
         [9568.],
         [9011.],
         ...,
         [9397.],
         [9531.],
         [9426.]],

        [[9487.],
         [9406.],
         [9305.],
         ...,
         [9420.],
         [9640.],
         [9718.]],

        [[9368.],
         [9670.],
         [9330.],
         ...,
         [9224.],
         [9558.],
         [9534.]]])


In [138]:
((gt - test)**2).mean()

tensor(2.2719e-09, grad_fn=<MeanBackward0>)

In [139]:
print(test)

tensor([[[-0.0132, -0.2497,  0.0147,  ..., -0.3016, -0.2678,  0.3225],
         [-0.5154, -0.6211,  0.6647,  ..., -0.1092, -0.8612, -1.1108],
         [ 0.2995,  0.9043, -0.6428,  ..., -0.4918,  0.6762,  0.0958],
         ...,
         [-0.2391, -0.7679, -0.1575,  ...,  0.1055, -0.5153, -1.3152],
         [-0.6596, -0.1150,  0.2063,  ..., -0.2385, -0.3908, -0.8548],
         [-0.7113,  0.7206,  0.2078,  ..., -0.7478,  0.0204, -0.6075]],

        [[-0.2663, -0.8407, -0.5942,  ..., -0.1754,  0.8408, -0.1712],
         [-0.2235, -0.1463,  0.2708,  ...,  1.0346,  0.1868, -0.5495],
         [ 0.0155,  0.3317, -0.2293,  ...,  0.4074, -0.4448, -1.3831],
         ...,
         [-0.4816,  0.8432,  0.1118,  ...,  0.0288, -0.8741,  0.8347],
         [ 0.0215, -0.5429, -0.1779,  ..., -0.9427, -0.7520,  0.7450],
         [-0.0605,  1.1092,  0.7791,  ...,  0.2658,  0.6505, -0.6987]],

        [[-0.7302,  0.4232,  0.8217,  ...,  0.4624,  0.4853, -1.3755],
         [ 0.5133,  0.1992, -0.7373,  ..., -0

In [140]:
gt

tensor([[[-0.0132, -0.2496,  0.0147,  ..., -0.3016, -0.2677,  0.3225],
         [-0.5154, -0.6211,  0.6647,  ..., -0.1092, -0.8611, -1.1108],
         [ 0.2995,  0.9042, -0.6428,  ..., -0.4918,  0.6761,  0.0958],
         ...,
         [-0.2392, -0.7678, -0.1575,  ...,  0.1055, -0.5153, -1.3152],
         [-0.6596, -0.1149,  0.2063,  ..., -0.2385, -0.3907, -0.8547],
         [-0.7113,  0.7206,  0.2078,  ..., -0.7478,  0.0205, -0.6075]],

        [[-0.2662, -0.8406, -0.5942,  ..., -0.1754,  0.8408, -0.1712],
         [-0.2234, -0.1462,  0.2708,  ...,  1.0345,  0.1868, -0.5495],
         [ 0.0155,  0.3317, -0.2293,  ...,  0.4073, -0.4448, -1.3831],
         ...,
         [-0.4815,  0.8431,  0.1118,  ...,  0.0288, -0.8740,  0.8346],
         [ 0.0216, -0.5428, -0.1779,  ..., -0.9427, -0.7520,  0.7451],
         [-0.0605,  1.1091,  0.7791,  ...,  0.2658,  0.6504, -0.6987]],

        [[-0.7301,  0.4232,  0.8216,  ...,  0.4624,  0.4852, -1.3755],
         [ 0.5133,  0.1992, -0.7373,  ..., -0